Squad member mutations
squadster/squadster-api pull request #41
Opened 2020-04-02 18:48 UTC by ARtoriouSs

WIP: Deletions of commanders not working well

2020-04-03 20:29 UTC, mirterious requested changes

2020-04-03 20:29 UTC, mirterious commented on spec/domain/helpers/permissions_spec.exs
> +            expect(user() |> Permissions.can_delete?(squad_member())) |> to(eq false)
Typo `can_update?`

2020-04-04 10:08 UTC, ARtoriouSs commented on spec/domain/helpers/permissions_spec.exs
> +            expect(user() |> Permissions.can_delete?(squad_member())) |> to(eq false)
Fixed

2020-04-04 10:17 UTC, mirterious approved these changes

2020-04-04 10:17 UTC, merged