Feature/mailer
squadster/squadster-api pull request #97
Opened 2020-12-05 21:39 UTC by str1nker

Added mailer module to Squadster

Configured with Mailgun

To make it work, you need to set ENV variables. I will send values directly
`export MAILGUN_API_KEY`
`export MAILGUN_DOMAIN`

Also, we have a test restricted account, so we can send mails to only 5 different people.
To be able to send mails to other people we need to add custom DNS, I will share accounts creds for that if necessary.

2020-12-05 22:02 UTC, ARtoriouSs requested changes

2020-12-05 22:02 UTC, ARtoriouSs commented on lib/squadster/accounts/tasks/notify.ex
> +    if user_with_settings.settings.email_notifications_enabled and user.email do
```elixir
%{settings: settings} = user |> Repo.preload(:settings)
if settings.email_notifications_enabled and user.email do
```

2020-12-05 22:02 UTC, ARtoriouSs commented on lib/squadster/mailer.ex
> +  @from "noreply@squadster.com"
Can we set it in env variable too? Maybe FROM_EMAIL or smth?

2020-12-05 22:02 UTC, ARtoriouSs commented on lib/squadster/mailer/emails.ex
> +defmodule Blog.Mailer.Emails do
Blog? :)

2020-12-05 22:02 UTC, ARtoriouSs commented on mix.exs
> +      {:poison, "~> 2.1", override: true},
Why do we need this change?

2020-12-05 22:17 UTC, ARtoriouSs commented
Also could you please add a test for Notify module? Just mock mailer and ensure it's called when the user have setting and email, and vise-versa

2020-12-05 22:35 UTC, str1nker commented on lib/squadster/accounts/tasks/notify.ex
> +    if user_with_settings.settings.email_notifications_enabled and user.email do
the next function requires user with settings

2020-12-05 22:35 UTC, str1nker commented on lib/squadster/mailer.ex
> +  @from "noreply@squadster.com"
yes we can

2020-12-05 22:35 UTC, str1nker commented on lib/squadster/mailer/emails.ex
> +defmodule Blog.Mailer.Emails do
Oops

2020-12-05 22:36 UTC, str1nker commented on mix.exs
> +      {:poison, "~> 2.1", override: true},
Because mailgun depends on poison 2.1

2020-12-06 12:41 UTC, ARtoriouSs commented on lib/squadster/accounts/tasks/notify.ex
> +    if user_with_settings.settings.email_notifications_enabled and user.email do
Ok

2020-12-06 13:19 UTC, mirterious approved these changes

2020-12-06 13:23 UTC, ARtoriouSs approved these changes

2020-12-06 13:23 UTC, merged